# Generated by Django 5.2.6 on 2025-09-25 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_noticiatcg_juego'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroCompras',
            fields=[
                ('id_carro', models.AutoField(primary_key=True, serialize=False)),
                ('total_sin_iva', models.IntegerField()),
                ('iva_compra', models.IntegerField()),
                ('precio_final', models.FloatField()),
                ('fecha_uso', models.DateTimeField(help_text='Para trazabilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(help_text='Incluye numeración', max_length=50)),
                ('comuna', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edicion', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('desarrollador', models.CharField(max_length=50)),
                ('sitio_web', models.CharField(help_text='Enlace al sitio web del juego', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_rol', models.CharField(help_text='Chamán (Admin), Guardián (Soporte), Aprendíz, Forastero (Usuario)', max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id_thread', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('estado_pedido', models.CharField(max_length=20)),
                ('total_sin_iva', models.IntegerField()),
                ('iva_compra', models.IntegerField()),
                ('precio_final', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrocompras')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('estado', models.CharField(max_length=15)),
                ('fecha_proceso', models.DateField()),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodopago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(choices=[('kit', 'Kit'), ('mazo', 'Mazo'), ('sobre', 'Sobre'), ('accesorio', 'Accesorio'), ('figura', 'Figura de colección'), ('plushie', 'Plushie Pokémon')], max_length=30)),
                ('tipo_accesorio', models.CharField(blank=True, choices=[('portamazo', 'Portamazo'), ('tapete', 'Tapete'), ('funda', 'Funda de cartas'), ('moneda', 'Moneda Pokémon'), ('oro', 'Oro holográfico'), ('plushie', 'Plushie Pokémon')], max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.IntegerField()),
                ('stock_total', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('cartas_por_mazo', models.IntegerField(blank=True, null=True)),
                ('cartas_por_sobre', models.IntegerField(blank=True, null=True)),
                ('tipo_sobre', models.CharField(blank=True, help_text='Booster, Starter, etc', max_length=25, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.edicion')),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.juego')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEnCarro',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_items', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('total_sin_iva', models.IntegerField()),
                ('fecha_uso', models.DateTimeField(help_text='Para trazabilidad')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrocompras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ForoPost',
            fields=[
                ('id_foro_post', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thread')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='ForoReporte',
            fields=[
                ('id_foro_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('estado', models.CharField(max_length=15)),
                ('foro_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foropost')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='foropost',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='carrocompras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
