# Generated by Django 5.2.6 on 2025-09-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrocompras_direccion_edicion_juego_metodopago_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
