# Generated by Django 5.2.6 on 2025-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_juego_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foropost',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fororeporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
