# Generated by Django 5.2.6 on 2025-09-26 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_foropost_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
