# Generated by Django 5.2.6 on 2025-09-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_thread_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='foropost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foro_imagenes/'),
        ),
    ]
