# Generated by Django 5.2.6 on 2025-09-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_foropost_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='core/img/hilos/'),
        ),
        migrations.AlterField(
            model_name='foropost',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
