# Generated by Django 5.2.6 on 2025-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_thread_imagen_alter_foropost_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foropost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='core/img/posts/'),
        ),
    ]
