# Generated by Django 5.2.6 on 2025-09-28 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_foropost_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrocompras',
            name='fecha_uso',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Para trazabilidad'),
        ),
        migrations.AlterField(
            model_name='carrocompras',
            name='iva_compra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrocompras',
            name='precio_final',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='carrocompras',
            name='total_sin_iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemencarro',
            name='cantidad_items',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemencarro',
            name='fecha_uso',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Para trazabilidad'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_proceso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
