# Generated by Django 5.2.6 on 2025-09-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_carrocompras_fecha_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='numero_dpto_casa',
            field=models.CharField(default=0, help_text='Número de departamento o casa', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(help_text='Calle y numeración', max_length=50),
        ),
    ]
