# Generated by Django 5.2.6 on 2025-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_direccion_numero_dpto_casa_alter_direccion_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='detalle',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='vencimiento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
