# Generated by Django 5.2.6 on 2025-10-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_metodopago_detalle_metodopago_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrocompras'),
        ),
    ]
